### ISSUE TITLE
Possible bug in timestamp

### ISSUE THREAD

**Issue by Niels86** [GrinPlusPlus/GrinPlusPlus#103]
Hi Dave,

After installing the newest version 7.2 downloaded from:
https://grinplusplus.github.io
And subsequently restoring my wallet (not sure if that has anything to do with the bug)
The time stamps for all transactions are set to 09-01-1970.
I am not sure if it is a bug or not since I do not know if the trasaction timestamps are stored on the blockchain but I though I would let you know in any case. What is 09-01-190 anyway, your birthday?

Cheers,

Niels

**Comment by DavidBurkett** [comment]
Not my birthday. The unix epoch is 1/1/1970,and that's what all dates are based on (milliseconds since epoch). Since your dates are showing just a few days after that, I probably read the datetime from the blockchain using seconds, but stored it where milliseconds were expected. I'll get this fixed in a future release. 
Thanks!

**Comment by Niels86** [comment]
Thx for explaining it to me Dave. You are fast in responding as always (based on what I observed on the Grin forum). Keep up the great work with Grin++

**Comment by DavidBurkett** [comment]
Fixed in 0.7.4. The date/times will still be wrong for your wallet, but any restores done in the future will no longer have this issue. If this is a problem, you can restore your account under a new username and then delete the old one.

**Comment by Niels86** [comment]
Yes, about that, how do you delete an account?

**Comment by DavidBurkett** [comment]
Manually for now. You have to delete `%userprofile%/.GrinPP/MAINNET/WALLET/<username>`, but I recommend just moving or renaming it until you've successfully restored.

**Comment by Niels86** [comment]
A, I see.

**Comment by Niels86** [comment]
Hi David, just now I did a restore wallet using Grin++ 7.4, however the timestamp in the restored wallet are stil set to the unix epoch 1/1/1970.

**Comment by DavidBurkett** [comment]
Thanks for reporting. I'll reopen until I get a chance to look at it

**Comment by Niels86** [comment]
Solved in 7.5.
