### ISSUE TITLE
(very) wrong dates for transactions

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#104]
Screenshot: https://i.gyazo.com/9080372e7d67f665f4758f2fb9ea0a48.png

Tons of them showing up as 1/19/1970.

Also, can you please show the full and exact timestamp down to the second of the time the transaction was made (rather than when the GPP app discovered it)? I posted more about this here: https://github.com/GrinPlusPlus/GrinPlusPlus/issues/88

**Comment by DavidBurkett** [comment]
It's a known issue, I just simply have not had time to fix it. Hopefully soon. I'll close this in favor of the previous issue
