### ISSUE TITLE
Won't Connect 

### ISSUE THREAD

**Issue by newsmaker22** [GrinPlusPlus/GrinPlusPlus#107]
I think this is the same problem as above...but just thought I would post.  
7.3 was working fine the past couple of days.  Today I tried to open it and it would not connect.  I closed it out and reopened...then got an error message 
"Error Occured. If another node is running, please close and try again.  Otherwise try deleting %userprofile.....
Error Command failed: GrinNode.exe--headless"

**Comment by DavidBurkett** [comment]
Fixed in 0.7.4
