### ISSUE TITLE
Failed to Retrieve Address 

### ISSUE THREAD

**Issue by BallowandSunder** [GrinPlusPlus/GrinPlusPlus#108]
Been having trouble with the wallet ever since the recent fork. 

So far everything has been fixed with the latest update, I can finally connect and access the features of the wallet again. 

Last issue standing, no HTTPS addresses generating...

![gpp error](https://user-images.githubusercontent.com/59857944/72971511-a87a9180-3d7e-11ea-81b7-12de35fc3e0f.jpg)

**Comment by DavidBurkett** [comment]
localtunnel is down, but you can send to https://<toraddress>.GrinPlusPlus.com which should work even better, since it never changes

**Comment by rgd212** [comment]
Where would you enter that (https://.GrinPlusPlus.com) having the same problem?

**Comment by DavidBurkett** [comment]
Sorry, github screwed up the display. Should be `https://<toraddress>.GrinPlusPlus.com`

**Comment by rgd212** [comment]
Where would i add http://<toraddress>.GrinPlusPlus.com in the program or file to make it work? Just verifying i am assuming the toraddress is the TOR: address below error "Failed To Retrieve Address"

**Comment by DavidBurkett** [comment]
That's just your new receive address. So when withdrawing from an exchange or mining pool, just enter your address: `http://<kv6ch......>.grinplusplus.com`

**Comment by BallowandSunder** [comment]
Thank you!
