### ISSUE TITLE
clickable commitment and actual timestamps

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#110]
Clicking on a transaction shows a drop down with more info, which is very nice and useful, many thanks! Can I please suggest a few improvements?

- make the commitment clickable to grinscan.net, rather than just copy to clipboard (all OSs have a handler for URLs to open the default browser)

- show the timestamps (YYYY-MM-DD HH:MM:SS) when the transaction got into the tx pool and when it was confirmed, both are very useful to know

- show the two timestamps (or at least one of them) in the main list rather than the relative human readable time ... 10/3/2019 is too vague (and very american, at least it could obey the OS's locale for date).

- show the maturity as a column in the table (as well as in the dropdown) ... not just to help the lazy ones (like me) from doing arithmetic, but it's useful to monitor when the maturity reaches some minimum number required by some Exchange I'm trading on (being quick after depositing is important).

**Comment by DavidBurkett** [comment]
The first suggestion is bad for privacy, so I'm not going to implement it.

I'll see what I can do about those other suggestions though.

**Comment by aleqx** [comment]
> The first suggestion is bad for privacy, so I'm not going to implement it.

I don't see that. It's not worse than what you (or the official wallet) already do, and all the info already exists, i.e. the commitment is already shown and can be copied to clipboard. I don't see why it shouldn't be clickable.

**Comment by DavidBurkett** [comment]
The protocol isn't bad for privacy, connecting to grinscan from your IP to lookup your commitment tells the grinscan server that you probably own that output. Using block explorers to look up your outputs for any coin is bad for privacy in general.

**Comment by aleqx** [comment]
> connecting to grinscan from your IP to lookup your commitment tells the grinscan server that you probably own that output.

Sorry but this goes against a few needed things, like proof of transaction and receipts ... and you seem to be advocating against them (i know you're not directly doing that). Grin badly needs a way for people to prove transactions to others (e.g. think disputes, exchange deposits/withdrawals, etc) and right now checking the commitment is all we have, and it's still flimsy ... basically you're proposing to make it even worse/inaccessible, rather than make it more accessible.

Also, copy/pasting or click a commitment URL in grinscan is the same thing.

Put up a warning upon clicking and let the user decide. Don't make the decision for them.

**Comment by aleqx** [comment]
All that being said, this is your baby ...

**Comment by DavidBurkett** [comment]
> Grin badly needs easier, verifiable ways for people to prove transactions (e.g. think disputes, exchange deposits/withdrawals, etc) and right now checking the commitment is all we have, and it's still flimsy

Right, and that's why we worked to add payment proofs for Grin++ 0.7.0+ and grin 3.0.0+. Both build payment proofs and should be able to export and verify them shortly.

> Let's not go full paranoia  

It's not paranoia, it's encouraging good privacy practices. Privacy is extremely difficult to get right, and most people don't think about the many ways they can leak info about their spending habits. That's why I've worked hard to ensure Grin++ always includes a full node, and have been advocating for the usage of TOR (and hopefully soon, non-interactive txs), among other things.

**Comment by aleqx** [comment]
Your work is very much appreciated. That said, Grin is suffering acutely from being too difficult to use. There is a threshold when too much security impedes functionality.

p.s. I have no idea how to use payment proofs in disputes with exchanges (exchanges have been clueless about Grin's functionality as it is ...). Trading Grin has been generally unpleasant and a pain. It feels worse than Bitcoin's first trading days.

**Comment by DavidBurkett** [comment]
> That said, Grin is suffering acutely from being too difficult to use.

100% agree, and I'm doing whatever I can to improve that. But the usability gains from adding a direct link to grinscan are marginal, at the cost of leaking a user's privacy without them realizing. I've provided a button to copy the commitment. Using grinscan merely requires pasting that commitment for those who deliberately choose to use a block explorer (realistically, there's no need, since Grin++ is already a full node and gives you the same info as a block explorer).

**Comment by aleqx** [comment]
> But the usability gains from adding a direct link to grinscan are marginal

Respectfully, 100% disagreed. In particular since you are making efforts to improve adoption. Think of the users new to Grin experiencing deposit/withdrawal issues with shit exchanges (shchanges). Grin++'s GUI is the closest to a (much needed) freindly GUI who could display a (popup/dropdown) message to the user right after finalization saying "See this transaction on the blockchain {here|url} if you need to offer proof that this transaction was accepted by the other party".

You should see the tickets I had with some shchanges and the pain you need to go through to explain "basic" Grin fundamentals to them ... which aren't that basic at all, because if they were then Grin would see a lot more adoption.

> Grin++ is already a full node and gives you the same info as a block explorer).

Sadly irelevant when dealing with disputes with another party.

**Comment by DavidBurkett** [comment]
Some of this has already been implementeed. I'll create a new ticket in the UI repo for tracking the remainder.
