### ISSUE TITLE
Unable to recevie transactions at http://externalip:3414

### ISSUE THREAD

**Issue by Niels86** [GrinPlusPlus/GrinPlusPlus#112]
In the past I used to mine at http://externalip:3414, has this changed to port 3415?
I am currently mining on port 3414 using GRIN++ 7.5 and am unable to receive payment.
A port scan shows only port 3415 to be open, 3414 is closed even though I forward it on my router. Has the port for receiving transactions been changed?

**Comment by DavidBurkett** [comment]
Grin++ no longer guarantees which port the listener will be opened on, since the underlying logic supports multiple logged in users at once. You can mine to your address listed in the "Receive" tab though (`http://<toraddress>.grinplusplus.com`). It is now a long-term address.

**Comment by Niels86** [comment]
Ok, that is a muchbetter solution indeed. Hopefully the last time I need to spam the mining pool.
