### ISSUE TITLE
double send !!

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#116]
I transferred 200 GRIN to an exchange and upon clicking Send and then "Yes" (to "Are you sure?") Grin++ created two transactions, each of 200 GRIN! Same session token used for both.

https://i.imgur.com/PHSz4vD.png

```
[2020-02-12 17:51:25.909] [info] Sending to: https://<snip>
[2020-02-12 17:51:25.910] [info] Calling (send) with data:
{"session_token":"YUmqpM1hR+s51bWXasRsxNcgwa/ik8vPlXVQX8x3JUILx/C5grnqxZrTfwo=","amount":200000000000,"fee_base":1000000,"selection_strategy":{"strategy":"SMALLEST","inputs":["09bd1ee3f5dd510b73876a455c147f01826eb6ceeeab6f229730fef446cd8cdaed","09f4b4696d5a4cd8d101e5af0fb7d8182b0a29a5d140008213f9956d20dbf7fe8a"]},"address":"https://<snip>","post_tx":{"method":"STEM"}}
[2020-02-12 17:51:25.966] [info] Sending to: https://<snip>
[2020-02-12 17:51:25.966] [info] Calling (send) with data:
{"session_token":"YUmqpM1hR+s51bWXasRsxNcgwa/ik8vPlXVQX8x3JUILx/C5grnqxZrTfwo=","amount":200000000000,"fee_base":1000000,"selection_strategy":{"strategy":"SMALLEST","inputs":["09bd1ee3f5dd510b73876a455c147f01826eb6ceeeab6f229730fef446cd8cdaed","09f4b4696d5a4cd8d101e5af0fb7d8182b0a29a5d140008213f9956d20dbf7fe8a"]},"address":"https://<snip>","post_tx":{"method":"STEM"}}
```

This is a problem regardless of whether it's an issue interpretting mouse clicks. The listener on the "Yes" button when clicked should prohibit further mouse/keyboard events. Better yet, no more than 1 transaction should be started from a single confirmation window, regardless of how many mouse/keyboard events the GUI button happens to capture.

**Comment by DavidBurkett** [comment]
It's using the same inputs, so only 1 transaction is valid. I'll see if I can recreate it somehow. Remind me which OS this was again. Win 8.1?

**Comment by DavidBurkett** [comment]
The whole UI has been replaced, so whatever issue may have existed before should be long gone. Feel free to reopen if it occurs again.
