### ISSUE TITLE
Download State Loop & Stuck at B: 221850

### ISSUE THREAD

**Issue by BallowandSunder** [GrinPlusPlus/GrinPlusPlus#117]
As the title says, when upgrading to the newest 0.7.5 Status: Download State Loops in percentage & Stuck at B: 221850.

Tried deleting, node folder but issue still persists.

Any other suggestions?

![issue](https://user-images.githubusercontent.com/59857944/74395449-323cde00-4dc4-11ea-9ec0-b2a48a098da2.jpg)

**Comment by DavidBurkett** [comment]
Delete `%userprofile%/.GrinPP/MAINNET/NODE/TXHASHSET` and retry.

**Comment by BallowandSunder** [comment]
It worked! Thank you!

**Comment by Z86-tech** [comment]
works! thank you!
