### ISSUE TITLE
Security Feature Request: Require Password to Send GRIN

### ISSUE THREAD

**Issue by mino827** [GrinPlusPlus/GrinPlusPlus#119]
**Request:**
For a future release I think it would be a great security feature to require a password to send any GRIN from the wallet.

**Rationale:**
I normally keep my wallet open to allow for incoming payments. If my PC gets compromised by a hacker they would be unhindered to drain my wallet. Forcing a password to be entered upon any send request minimizes the potential for this happening.
There are other wallets available that have this exact functionality, and rightly so.

**Comment by DavidBurkett** [comment]
This was included as part of 1.0.0
