### ISSUE TITLE
Receive Error: "Failed to connect to TOR" message on initial section load every time

### ISSUE THREAD

**Issue by binarygeek** [GrinPlusPlus/GrinPlusPlus#120]
**OS:** Mac
**Status:** Running (DB synced)
**Background:** Clicking on "Receive" button causes the error below to be displayed.
**Error message:**
> "ERROR: Failed to connect to TOR
> 
> Help: https://grinplusplus.github.io/support"

When the "retry" icon is clicked the addresses populate with addresses:

> http://ADDRESS.grinplusplus.com
> 
> TOR: ADDRESS

Every time I click away (for example to "wallet" button) and click back to receive button...I get the same error above...only for the addresses to show after clicking on "refresh icon"

NOTE: Above HELP URL (https://grinplusplus.github.io/support) in error message above returns a 404 (have not created an issue for this)

**Comment by DavidBurkett** [comment]
Ok, so you're generating a tor address fine, but only after clicking refresh? That's not an issue I've come across, but I do almost all testing on windows and linux. I'll see if I can recreate.

Which Mac OS version are you running?

**Comment by binarygeek** [comment]
I'm not trying to generate a tor address. I just clicked on the "Receive" button to see what it did. That's when I saw the error with the reload icon. When the support url didn't work figured I'd try the reload which gave me the addresses.

MacOS Catalina 10.15.2

**Comment by Tigerix** [comment]
Microsoft Windows [Version 10.0.18363.693]

I have the same issue. At first clicking on the refresh icon gave me 2 URLs. But now even after restarting I only receive the error message without the URLs.

ERROR: Failed to connect to TOR

**Comment by DavidBurkett** [comment]
I don't know what's causing the issue. Perhaps antivirus interfering with tor?

Here's a workaround for now. 

     * On windows: 
           - Download and extract https://keybase.pub/dburkett/tor.zip. Double click RunTor.bat and then reopen Grin++

     * On mac: 
           - Install homebrew (https://brew.sh) - From terminal, enter /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
           - Install tor (https://2019.www.torproject.org/docs/tor-doc-osx.html.en) - From terminal, enter brew install tor
           - Start tor - From terminal, enter tor --ControlPort 3423 --SocksPort 3422 --HashedControlPassword "16:906248AB51F939ED605CE9937D3B1FDE65DEB4098A889B2A07AC221D8F"
           - Reopen Grin++

**Comment by Tigerix** [comment]
Excellent! The workaround is working! Thanks! :)

I have only Microsoft Windows Defender running. No other Antivirus Software!

**Comment by DavidBurkett** [comment]
I've done a lot of work to improve the reliability of tor in the upcoming v1.0.3 release. Please reopen if the issue persists.
