### ISSUE TITLE
Rpc which return only retrieve transactions

### ISSUE THREAD

**Issue by StephanDre** [GrinPlusPlus/GrinPlusPlus#122]
hey, i need command rpc which give me only retrieve type transactions.

**Comment by DavidBurkett** [comment]
I'm doing a bunch of work on the APIs, so I can implement this now. Can you elaborate a bit? You just need a way to filter the transactions by type?

**Comment by StephanDre** [comment]
yes, i need only filter type of transactions, pls give me feedback and link
to your docs API when you done.

niedz., 12 kwi 2020 o 10:52 David Burkett <notifications@github.com>
napisał(a):

**Comment by DavidBurkett** [comment]
v1.0.0's owner API has a method called "list_txs" which allows you to filter by statuses and date/time ranges:

https://github.com/GrinPlusPlus/GrinPlusPlus/blob/master/include/API/Wallet/Owner/OwnerServer.h#L206-L226
