### ISSUE TITLE
Can't send Grin to myself to consolidate UTXOs!

### ISSUE THREAD

**Issue by Tigerix** [GrinPlusPlus/GrinPlusPlus#123]
I have tried to send all my Grin UTXOs to myself within Grin++ to consolidate my UTXO.
But for some reason the http and the file method doesn't work.
Is this not possible yet?

**Comment by DavidBurkett** [comment]
It's not currently implemented, but why would you want to? Consolidating UTXOs is bad for privacy, and increases the fee you'll pay for future txs

**Comment by Tigerix** [comment]
Oh I didn't know that... I did it because I wanted to obfuscate the different transaction values in my wallet.

**Comment by Tigerix** [comment]
Why does it increase future fees?
I thought it reduces them, since there are less utxos to include in Future transactions.

**Comment by DavidBurkett** [comment]
obfuscate from who? The amounts are hidden on-chain.

Grin actually decreases fee per input in a transaction because of the way mimblewimble's pruning works. Spending inputs results in a smaller chain.

**Comment by Tigerix** [comment]
Oh thanks, I learned something new today!
