### ISSUE TITLE
No delete wallet option

### ISSUE THREAD

**Issue by nickrod** [GrinPlusPlus/GrinPlusPlus#124]
I'm trying to delete an old test wallet but can't figure it out, maybe I'm missing something obvious or it hasn't been implemented yet.

**Comment by DavidBurkett** [comment]
Sorry, I somehow missed this issue. Wallet deletion was not implemented out of an abundance of caution. If you are confident that's what you want to do though, just delete the appropriate folder inside of `C:\users\<username>\.GrinPP\MAINNET\WALLET\` (windows), or `~/.GrinPP/MAINNET/WALLET/` (Mac/Linux). There's a folder in there for each wallet.
