### ISSUE TITLE
Don't start in MacOs

### ISSUE THREAD

**Issue by Ericktz** [GrinPlusPlus/GrinPlusPlus#127]
I have downloaded v1.0.2 dmg... moved into Applications/...

When I run it, an error has occurred:
ENOENT. no such file or directory, open '/Users/Erick/.GrinPP/MAINNET/server_config.json'

I don't have the folder '.GrinPP' into my user folder. How Should I proceed?

**Comment by DavidBurkett** [comment]
Ah, my bad. Open the terminal and type:

`mkdir -p ~/.GrinPP/MAINNET && touch ~/.GrinPP/MAINNET/server_config.json && echo "{}" > ~/.GrinPP/MAINNET/server_config.json`

Press enter and then you should be good to open Grin++

**Comment by Ericktz** [comment]
:O... to solved. I downloaded 1.0.1, this version creates the folder... and after running it. I delete and run the 1.0.2 version.

**Comment by DavidBurkett** [comment]
I'll get this fixed for the next version. Thanks for reporting
