### ISSUE TITLE
ENOENT. no such file or directory, open '/Users/me/.GrinPP/MAINNET/server_config.json'

### ISSUE THREAD

**Issue by daldwinc** [GrinPlusPlus/GrinPlusPlus#128]
Hi,

Upon opening Grin++ v1.0.2 on MacOS 10.15.4, I get the error in the subject line. I can't dismiss it or move on in any way. If I close and re-open the app, I get the same thing.

It seems like the folder .GrinPP was not created in my homedir.

**Comment by DavidBurkett** [comment]
The fix will be released soon, but here's a workaround: https://github.com/GrinPlusPlus/GrinPlusPlus/issues/127#issuecomment-626934766

**Comment by daldwinc** [comment]
Perfect. Thanks for the quick reply.
