### ISSUE TITLE
Node isn't running

### ISSUE THREAD

**Issue by ahilis** [GrinPlusPlus/GrinPlusPlus#130]
Doesn't work after update from 1.0.2
Tried to reinstall, didn't help
Windows 10
![image](https://user-images.githubusercontent.com/6560240/82180927-f2bdea80-98fa-11ea-888f-2fa69a026bbe.png)

**Comment by katsaplias** [comment]
same for me

**Comment by DavidBurkett** [comment]
Revert to 1.0.2 for now while we look at this

**Comment by katsaplias** [comment]
even the upgrade to 1.0.6 didn't help (W10x64)

**Comment by ahilis** [comment]
Update to 1.0.6 has helped to run a Node but the balance is empty now =/

**Comment by DavidBurkett** [comment]
The fix for @ahilis was to close Grin++ and reinstall 1.0.6.

@katsaplias Can you create a new issue and give as many details as you can. List all steps you tried. Thanks :)
