### ISSUE TITLE
MacOS v1.0.6: Node isn't running

### ISSUE THREAD

**Issue by daldwinc** [GrinPlusPlus/GrinPlusPlus#132]
I had a power outage that rebooted my Mac (10.15.5), and now I can't get Grin++ to start properly. I've tried doing a `pkill Grin`, rebooting, splat+Q to close.. nothing seems to get it going again. 

The UI displays the Grin++ logo and the error "! Node isn't running"

I noticed that when I quit the UI, one process stays running:

/Applications/Grin++.app/Contents/Resources/app.asar.unpacked/bin/tor/tor --ControlPort 3423 --SocksPort 3422 --DataDirectory ./tor/data3423 --HashedControlPassword <redacted> -f ./tor/.torrc --ignore-missing-torrc

Any advice?

**Comment by DavidBurkett** [comment]
Your node data was probably corrupted. Try deleting ~/.GrinPP/MAINNET/NODE and reopening it.

**Comment by daldwinc** [comment]
That worked like a charm. Thanks!

I'll leave it up to you if you want to close this or possibly turn it into a feature request for the next version. Perhaps a more detailed error message or a recovery suggestion could be shown in the UI?

Cheers,
Dave
