### ISSUE TITLE
Full screen not working with 1366x768 resolution

### ISSUE THREAD

**Issue by nickrod** [GrinPlusPlus/GrinPlusPlus#133]
Not sure what's happening, but if I run the program (Linux AppImage 1.0.6) on my laptop with 1366x768, then I am not able to full screen the application and it's difficult to see the status bar on the bottom. Then on a different computer with the same OS it's working fine in 1920x1080.

**Comment by DavidBurkett** [comment]
Yea, the minimum window size is quite large. We're working on ways to make it require a little less real estate. Grin just had a planned hardfork a few minutes ago, so we're working on a new version (v1.1) to support it. I'll see if I can improve it as part of that release.

**Comment by nickrod** [comment]
Ah ok nice, so I picked the perfect time to submit these issues.

**Comment by DavidBurkett** [comment]
I reduced the height of the window by 60px. Let me know if that's not enough.

**Comment by nickrod** [comment]
It's working now, thanks for including that.
