### ISSUE TITLE
Receive address not being generated

### ISSUE THREAD

**Issue by nickrod** [GrinPlusPlus/GrinPlusPlus#135]
This is using 1.0.6 AppImage on MX Linux (Debian based distro), the receive address is never generated and hangs on "Trying to get your address, please wait...".

**Comment by DavidBurkett** [comment]
Yea, I have a pinned message in the telegram group about that, but I should really do better about keeping the github issues list up to date. We have very few Linux users, so it unfortunately doesn't get near as much attention from us as the windows and Mac versions. 

Here's the workaround:

```
v1.0.6 for Linux does not generate the tor address correctly. A workaround is to use the deb instead of the AppImage. After installing the deb, if you sudo chmod 777 /opt/Grin++/resources/app.asar.unpacked/bin/tor and then open it, you should be good. 
```

**Comment by nickrod** [comment]
Ok thanks, I'll give it a try. Can I just install tor separately and use that or does it have to be the one bundled with Grin++?

**Comment by DavidBurkett** [comment]
There's logic to fallback to using any tor that's on the path, though I haven't done much testing around that.

**Comment by nickrod** [comment]
Just to let you know, I did install tor separately and it picked it up without needing to do any extra configuration. So works now with the AppImage.
