### ISSUE TITLE
Chrome-sandbox fatal error on startup

### ISSUE THREAD

**Issue by nickrod** [GrinPlusPlus/GrinPlusPlus#136]
This is using the AppImage 1.0.6 on MX Linux, if I run the program from the command line I can see this error: 

$ ./GrinPlusPlus-1.0.6.AppImage
[4478:0716/181344.623970:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_GrinPlLkwZ4F/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

I don't know what's happening but it seems to be a common error just from searching online, for now I can get around this by passing the command line argument --no-sandbox and it works fine.

**Comment by nickrod** [comment]
Maybe a quick workaround would be to hard code the --no-sandbox argument into the AppImage by default.

**Comment by DavidBurkett** [comment]
Cool. Thanks for investigating!

**Comment by DavidBurkett** [comment]
There does not appear to be a way to do this by default for electron-based apps. This is an issue that has been logged against electron long ago, with no resolution. Closing for now, but will reopen if a solution appears in the future.
