### ISSUE TITLE
the grin is hard fork, do's grin++ supported ? 

### ISSUE THREAD

**Issue by inkbx** [GrinPlusPlus/GrinPlusPlus#137]
Hello, the grin node is hard fork a weeks ago, do's grin++ supported now?

**Comment by DavidBurkett** [comment]
There is a windows version here: https://github.com/GrinPlusPlus/GrinPlusPlus/releases/tag/v1.1.0-beta.3

The Mac and Linux versions are in progress

**Comment by inkbx** [comment]
some address in grin++ can receive grin coins some times can't. 

Dos the grin wallet different version cause ?

**Comment by DavidBurkett** [comment]
Try with 1.1.0. It should work more reliably
