### ISSUE TITLE
Linux (Debian) 1.1.0-beta.7 AppImage bus error

### ISSUE THREAD

**Issue by nickrod** [GrinPlusPlus/GrinPlusPlus#138]
I'm getting an error when running the latest beta 7, starts up initially but fails shortly after with errors:

[6475:0725/111258.359426:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
11:12:59.077 › Error: HttpError: 404 Not Found
"method: GET url: https://github.com/GrinPlusPlus/GrinPlusPlus/releases/download/v1.1.0-beta.7/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Sat, 25 Jul 2020 18:12:58 GMT",
  "content-type": "text/plain; charset=utf-8",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=f0ZHe29LzSBZO5x6F8Z%2Fu2Sy0lbhaH4nx46GZchDfD2JN8wTCfA9nDnAep3b7MogD61tX0zA%2BQDWMwMEhIvvAVuRnf2u4VSqyX21IdyZzYruboP%2BRFJX5mVBsRRHZ8zwjMMUDqWk0NbfQ%2FXg6sHt8a4j%2BUtG2rxI2kx6Uxd5uWeShd2A6j4J2y2iJzYC%2Brd%2B5KWbyBH0u2aLKo4fFGiXSUltP9lwRSPOpjIzEzOuC6Vd7f1FrNJjza7zs9%2B6unXNFVKV%2BQ5MXEVWMUx%2F07UDiQ%3D%3D--Ivui4tPxiGiZkXXz--UVUHqIggxB8qozu3zyR6Jw%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.1316244834.1595700778; Path=/; Domain=github.com; Expires=Sun, 25 Jul 2021 18:12:58 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Sun, 25 Jul 2021 18:12:58 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "C90C:089B:2C5D1A:3EBE30:5F1C762A"
}
    at createHttpError (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2569:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:6445) UnhandledPromiseRejectionWarning: HttpError: 404 Not Found
"method: GET url: https://github.com/GrinPlusPlus/GrinPlusPlus/releases/download/v1.1.0-beta.7/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Sat, 25 Jul 2020 18:12:58 GMT",
  "content-type": "text/plain; charset=utf-8",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=f0ZHe29LzSBZO5x6F8Z%2Fu2Sy0lbhaH4nx46GZchDfD2JN8wTCfA9nDnAep3b7MogD61tX0zA%2BQDWMwMEhIvvAVuRnf2u4VSqyX21IdyZzYruboP%2BRFJX5mVBsRRHZ8zwjMMUDqWk0NbfQ%2FXg6sHt8a4j%2BUtG2rxI2kx6Uxd5uWeShd2A6j4J2y2iJzYC%2Brd%2B5KWbyBH0u2aLKo4fFGiXSUltP9lwRSPOpjIzEzOuC6Vd7f1FrNJjza7zs9%2B6unXNFVKV%2BQ5MXEVWMUx%2F07UDiQ%3D%3D--Ivui4tPxiGiZkXXz--UVUHqIggxB8qozu3zyR6Jw%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.1316244834.1595700778; Path=/; Domain=github.com; Expires=Sun, 25 Jul 2021 18:12:58 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Sun, 25 Jul 2021 18:12:58 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "C90C:089B:2C5D1A:3EBE30:5F1C762A"
}
    at createHttpError (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2569:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:6445) UnhandledPromiseRejectionWarning: HttpError: 404 Not Found
"method: GET url: https://github.com/GrinPlusPlus/GrinPlusPlus/releases/download/v1.1.0-beta.7/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "date": "Sat, 25 Jul 2020 18:12:58 GMT",
  "content-type": "text/plain; charset=utf-8",
  "server": "GitHub.com",
  "status": "404 Not Found",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "1; mode=block",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "set-cookie": [
    "_gh_sess=f0ZHe29LzSBZO5x6F8Z%2Fu2Sy0lbhaH4nx46GZchDfD2JN8wTCfA9nDnAep3b7MogD61tX0zA%2BQDWMwMEhIvvAVuRnf2u4VSqyX21IdyZzYruboP%2BRFJX5mVBsRRHZ8zwjMMUDqWk0NbfQ%2FXg6sHt8a4j%2BUtG2rxI2kx6Uxd5uWeShd2A6j4J2y2iJzYC%2Brd%2B5KWbyBH0u2aLKo4fFGiXSUltP9lwRSPOpjIzEzOuC6Vd7f1FrNJjza7zs9%2B6unXNFVKV%2BQ5MXEVWMUx%2F07UDiQ%3D%3D--Ivui4tPxiGiZkXXz--UVUHqIggxB8qozu3zyR6Jw%3D%3D; Path=/; HttpOnly; Secure; SameSite=Lax",
    "_octo=GH1.1.1316244834.1595700778; Path=/; Domain=github.com; Expires=Sun, 25 Jul 2021 18:12:58 GMT; Secure; SameSite=Lax",
    "logged_in=no; Path=/; Domain=github.com; Expires=Sun, 25 Jul 2021 18:12:58 GMT; HttpOnly; Secure; SameSite=Lax"
  ],
  "content-length": "40",
  "x-github-request-id": "C90C:089B:2C5D1A:3EBE30:5F1C762A"
}
    at createHttpError (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (/tmp/.mount_GrinPlCoJgEn/resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2569:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(node:6445) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6445) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6445) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6445) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DavidBurkett** [comment]
The Linux version is not quite ready yet. I meant to remove it before publishing the last release. The next beta I push will hopefully have a working AppImage.

I'll comment here when it's ready. Sorry about the delays. The last hardfork required soo many changes. I've been swamped trying to get it working on all 3 platforms.

**Comment by nickrod** [comment]
No problem David, thanks for your work on this, I'm eager to try it out.

**Comment by DavidBurkett** [comment]
Can you give it a shot now? I only did minimal testing on linux, but it seemed to be working now

**Comment by nickrod** [comment]
Yes, it's working great now, thanks for this update!
