### ISSUE TITLE
Client update alerts stopped in v1.1.0

### ISSUE THREAD

**Issue by daldwinc** [GrinPlusPlus/GrinPlusPlus#140]
Hey,

I upgraded Grin++ to v1.1.0 by following the prompt within the client (great feature btw).

Since then I have noticed a number of new releases on GitHub, but no alerts in the client. I've tried restarting it multiple times over the last few days hoping that it would kick the tires, but no luck.

Any advice?

**Comment by DavidBurkett** [comment]
I'm still getting alerts. Which operating system are you using?

**Comment by daldwinc** [comment]
Sorry, I should have included that in my original report: MacOS 10.15.6 (19G73).

**Comment by DavidBurkett** [comment]
You're right, my Mac's v1.1.0 is not prompting either. Thanks for reporting this issue.
