### ISSUE TITLE
Unknown exception when sending GRIN.

### ISSUE THREAD

**Issue by bertwijnhout** [GrinPlusPlus/GrinPlusPlus#143]
When I try to send GRIN to the KuCoin exchange an "Unknown exception" message appears in red at the bottom of the GUI.
I am using Grin++ v1.1.3 on Windows.

**Comment by DavidBurkett** [comment]
Can you email me your wallet logs? On windows, they're at `%userprofile%/.GrinPP/MAINNET/LOGS/Wallet.log`. For mac/linux, they're at `~/.GrinPP/MAINNET/LOGS/Wallet.log`. 
davidburkett38@gmail.com

**Comment by DavidBurkett** [comment]
Resolved by reinstalling 1.1.3
