### ISSUE TITLE
Grin tor address not reachable, http address is working Grin++ 1.1.3

### ISSUE THREAD

**Issue by Niels86** [GrinPlusPlus/GrinPlusPlus#144]
My Grin tor address in Grin++ v1.1.3 is not reachable. I tested it using:
http://grinchck.ahcbagldgzdpa74g2mh74fvk5zjzpfjbvgqin6g3mfuu66tynv2gkiid.onion/
I am not sure why since the http address is working and tor is not blocked by my internet provider (Tor browser works fine).
Outgoing i have 15 peers, in-going none.

**Comment by davidtavarez** [comment]
what do you mean with "not working"? you mean, isn't reachable?

**Comment by Niels86** [comment]
Sorry, yes that is what I mean. It is not reachable for some reason.

**Comment by DavidBurkett** [comment]
Are you talking about the grin1 address? That's not a tor address. It's a slatepack address. Under the hood it uses tor, but you're not able to access it directly since the address is encoded in a different way than standard onion addresses.

**Comment by Niels86** [comment]
A ok, so that it does not work when I test it using http://grinchck.ahcbagldgzdpa74g2mh74fvk5zjzpfjbvgqin6g3mfuu66tynv2gkiid.onion/
that is actually to be expected.
Sorry, I had a lot of testing and resetting since my http address was not working either for a while so I tested both using that tool. My http address is working again, so apparently among deleting node data, restoring accounts etc. I somehow accidentally fixed the problem.
