### ISSUE TITLE
Low balance display issue

### ISSUE THREAD

**Issue by l33d4n** [GrinPlusPlus/GrinPlusPlus#148]
When the balance is too low the balance isn't displayed well

![image](https://user-images.githubusercontent.com/8020386/91366246-cb4db680-e835-11ea-8df2-d294d3cec85f.png)

**Comment by davidtavarez** [comment]
Fixed! Thanks for reporting. (https://github.com/GrinPlusPlus/GrinPlusPlusUI/commit/2d6c291561a9d19c1fd0109be59b29b3f2b36677)

**Comment by l33d4n** [comment]
Great! Thanks.
