### ISSUE TITLE
Stuck at initializing node... after deleting server_config.json

### ISSUE THREAD

**Issue by rojomisin** [GrinPlusPlus/GrinPlusPlus#159]
budgie/ubuntu x64 linux
grin 1.1.4beta7

Node is fully synced, but only 2 peers were appearing.  I checked the settings and it showed min 10 max 50.  I checked the server_config.json and it was min 2. Since the settings didn't match between them, I closed out of gpp, whacked the ~/.GrinPP/MAINNET/server_config.json and restarted.  Upon first launch it is stuck at Initializing node indefinitely.  Closing again and relaunching allows it to get right in.

This laptop is not screaming fast, but is 8 core hp elitebook with 8gb ram.

**Comment by DavidBurkett** [comment]
We've changed how we handle server_config.json loading & updating to avoid races where the front-end and back-end were both trying to access and/or modify the file at similar times. Let us know if you experience this issue again.
