### ISSUE TITLE
The Grin++ address cannot turn green

### ISSUE THREAD

**Issue by whm361** [GrinPlusPlus/GrinPlusPlus#172]
I set up Grin++ in China, the address is always  orange. 
1.Install Torbrowser , it cannot work.
2.Open VPN ,and set up Socks5Proxy 127.0.0.1:19181. The Torbrowser can run normal.
3.Copy the paramater setting to the file .torrc.

Bridge obfs4 38.229.33.83:80 0BAC39417268B96B9F514E7F63FA6FBA1A788955 cert=VwEFpk9F/UN9JED7XpG1XOjm/O8ZCXK80oPecgWnNDZDv5pdkhq1OpbAH0wNqOT6H6BmRQ iat-mode=1
Bridge obfs4 192.95.36.142:443 CDF2E852BF539B82BD10E27E9115A31734E378C2 cert=qUVQ0srL1JI/vO6V6m/24anYXiJD3QP2HgzUKQtQ7GRqqUvs7P+tG43RtAqdhLOALP7DJQ iat-mode=1
Bridge obfs4 37.218.245.14:38224 D9A82D2F9C2F65A18407B1D2B764F130847F8B5D cert=bjRaMrr1BRiAW8IE9U5z27fQaYgOhX1UCmOpg2pFpoMvo6ZgQMzLsaTzzQNTlm7hNcb+Sg iat-mode=0
..........
..........
Socks5Proxy 127.0.0.1:19181
UseBridges 1

4.Run Grin++ again, it can not run normal.
How to sovle the problem?

**Comment by davidtavarez** [comment]
Please check this comment https://github.com/GrinPlusPlus/GrinPlusPlus/issues/171#issuecomment-820193621

**Comment by topmin** [comment]
First, there must be a VPN, and then open C:\users\administrator\Grinpp\mainnet\tor directory. Create a named .Torrc file, Note that the file name is an period connection "torrc". and then open it with a text editor, write a unique line:

> Socks5Proxy 127.0.0.1:1080

"1080" at the end of the line is the VPN port. It is written according to the settings of your VPN software. It is generally 1080. There are others, depending on your VPN software.

Note this There is only one line in the torrc file, which is similar to the bridge line below. Maybe there is a bridge line in other countries, but not in China. China can only use VPN, not bridge.

`Bridge obfs4 IP:PORT FINGERPRINT cert=CERT iat-mode=0`
`Bridge obfs4 IP:PORT FINGERPRINT cert=CERT iat-mode=0`
`Bridge obfs4 IP:PORT FINGERPRINT cert=CERT iat-mode=0`
`UseBridges 1`

Note: the above lines cannot exist in Torrc file!
