### ISSUE TITLE
"The node processing is running but not responding, this is unusual, but don’t worry we just need to restart."

### ISSUE THREAD

**Issue by box1111111** [GrinPlusPlus/GrinPlusPlus#178]
I using Linux mint and the wallet grin++ v.1.2.6. After upgrading it runs normal but since some days the wallet cannot be startet:
"The node processing is running but not responding, this is unusual, but don’t worry we just need to restart."
The node log file:
![image](https://user-images.githubusercontent.com/6226667/135436627-4885bf00-06b0-4bef-bcc7-afde8215f222.png)

**Comment by chadluby** [comment]
Were you able to figure out the situation
