### ISSUE TITLE
GRIN++ Wallet not responding

### ISSUE THREAD

**Issue by rockwhite** [GrinPlusPlus/GrinPlusPlus#181]
I want to sell my GRIN which is currently in Vite Wallet.  Vite is currently not working for past several months so it suggests restoring in another wallet.  So I downloaded GRIN++ Wallet on my Mac.  But it just keeps spinning and has a red dot at the bottom saying "Status: Not Connected".  I tried in my MalwareBytes to turn off App Block and Malware Protection but to no avail.  Can anyone help?  Thanks!

**Comment by davidtavarez** [comment]
Closing due inactivity.
