### ISSUE TITLE
Fixed  The node process is not running don't worry you just need a restart.... 

### ISSUE THREAD

**Issue by djabbir** [GrinPlusPlus/GrinPlusPlus#183]
Hi I recently installed Grin++ v1.2.6 Windows 10 64x I managed to create  a wallet but then I started getting the node process not working message now I'm unable to log in the message comes straight away I need help 
1. I checked this folder for the grin NODE it looks present 
C:\Users\PC\AppData\Local\Programs\GrinPlusPlus\resources\app.asar.unpacked\bin
2. I have also tried the CMD command but I got " not recognized as an internal or external operable program or batch file.
3. I also tried to delete the node file from C:\Users\PC\.GrinPP\MAINNET\NODE to no avail

**Comment by djabbir** [comment]
I fixed this issue by uninstalling Grin++ V1.2.6 then downloading Grin 5.0.3 at the this link
 
https://grin.mw/download 
A
after extracting this file please  reinstalled Grin ++ V1.2.6 and re sync my wallet and it worked took some time to sync but it worked.

**Comment by davidtavarez** [comment]
Download v1.2.7 https://github.com/GrinPlusPlus/GrinPlusPlus/releases/tag/v1.2.7
