### ISSUE TITLE
Node isn't pruning connection with inactive peers 

### ISSUE THREAD

**Issue by davidtavarez** [GrinPlusPlus/GrinPlusPlus#190]
`num_inbound` is never going down.

![image](https://user-images.githubusercontent.com/337107/151958800-f3d3087f-ad4e-488a-97ce-a22ac3ba946e.png)

This might be related to https://github.com/GrinPlusPlus/GrinPlusPlus/issues/187

**Comment by MCM-Mike** [comment]
I can confirm this behavior as I am working close with @davidtavarez for the setup of our nodes.
All public nodes are showing this behavior.
