### ISSUE TITLE
Grin++ unable to login. Status 2/4 Downloading state will not progress

### ISSUE THREAD

**Issue by Technificent** [GrinPlusPlus/GrinPlusPlus#199]
I am attempting to open Grin++ on my PC and I am getting a Status 2/4 Downloading state that never seems to progress. It shows a percentage  but it hardly progresses and it's been two days.
Has anyone experienced this issue?

**Comment by davidtavarez** [comment]
which version are you running?

**Comment by Technificent** [comment]
V1.2.6
