### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by zgreat** [GrinPlusPlus/GrinPlusPlus#21]
Sorry this isn't really an issue more of a question do you have any plans for Linux support?

**Comment by DavidBurkett** [comment]
Eventually, but my main focus is on Windows right now, since the official Grin client already supports Linux. https://github.com/mimblewimble/grin

**Comment by DavidBurkett** [comment]
I should elaborate more. Everything was written to be cross-platform by relying on cmake, the stl, and cross-platform dependencies. The only exception is sockets which use winsock2, but were well isolated by wrapping most of their uses in SocketHelper.cpp, knowing that they would soon be switched to something like boost sockets. I haven't tried to build in anything other than vs2017, but I suspect it would only require tweaking cmake config files once winsock is replaced. It will require cmake and a compiler with C++17 support though.

**Comment by DavidBurkett** [comment]
See https://github.com/GrinPlusPlus/GrinPlusPlus/issues/43
