### ISSUE TITLE
Grin ++ / restart wallet issues 

### ISSUE THREAD

**Issue by shnoah641** [GrinPlusPlus/GrinPlusPlus#215]
I am unable to keep my Grin ++ wallet running for more than 4 hours without it popping back up needing to restart my wallet and when I click restart wallet nothing happens.

 I literally have to force close the application in order for the wallet to load properly to have it 4 hours later do the same thing again. To get paid on the pool I run on with my wallet has to be reachable and with the wallet closed and not running it will refuse to pay me if it cannot stay running 24/7. I'm having this issue on both Windows 10 and 11 operating system. I also should mention I have no other programs running accept the Grin ++ application.

**Comment by galiy** [comment]
I am having the same problem. Please solve it.

**Comment by jwinterm** [comment]
I have a similar issue (maybe) on macos using v1.2.7. If I leave the wallet open for a while my node goes into STATUS: Not Connected and I have to close the app and restart it.

**Comment by galiy** [comment]
Is it fixed?

**Comment by davidtavarez** [comment]
if you need further help with this issue you can join [Grin++ on Telegram](https://t.me/GrinPP).

**Comment by shnoah641** [comment]
Yes it worked itself out turned out it was error on my network side but all
I had to do was turn on upnp.
