### ISSUE TITLE
Grin ++ 1.2.8 Tor bridges does not work

### ISSUE THREAD

**Issue by shnoah641** [GrinPlusPlus/GrinPlusPlus#219]
So I put in the bridges for my grin wallet it makes the address go green but if I restart or exit the wallet and try to restart the computer and reload the application it just sits on orange again even with the settings still active. I even left the application overnight to see if anything changes but unless I disable bridges and the repaste it back in again after restarting the wallet it does nothing.

**Comment by shnoah641** [comment]
Below is what I inputed into the tor bridge lines:


obfs4 [188.67.235.74:3876](http://188.67.235.74:3876/) B7D366ECA3443481C1F4B774E50C2DBA6D7948CE cert=BeYU8A5nw3fTRxA8DphYvQrex3nV8StK3wG6/ZbFpmliJymdzAEafGdiD/zDw3wKIdJpLQ iat-mode=2
obfs4 [94.140.115.5:443](http://94.140.115.5:443/) 28CA5C42872FD6FBEDA9658F2A63618776A54416 cert=GYIbAY5uvHsfB9lBMGOS9/0+nU3uIO+DdxBZsOWwfwZsjUlxz3YIOqFKQg5GRzINiy1jAw iat-mode=0
obfs4 [162.19.245.215:42001](http://162.19.245.215:42001/) 9953E998B6C65012A49A6B48BE42065E6559804A cert=vBTn9bnFVGxcL067lP3zwqkN1gKv9VsKVZIgUIYOirVXd0D2KaPQnZjgKTgIt1sk1sZyFA iat-mode=0
obfs4 [2001:19f0:4401:87c:5400:3ff:feb7:8cfc]:4444 55346F385B6FB7069D1588CE842DBE88F90F90C5 cert=fbtptOz8dA1Sz6Fl4i0k8KNqBVt8ueGmBHUBixB1/0QCyxwct9w4TwyXJe9kjwQCeR9SVw iat-mode=0
UseBridges 1

**Comment by davidtavarez** [comment]
This is how you add them:
<img width="1312" alt="Screenshot 2023-04-13 at 22 31 43" src="https://user-images.githubusercontent.com/337107/231876294-f2dbf0af-b418-4522-bfa9-004427a1bc6c.png">

**Comment by shnoah641** [comment]
It worked thank you so much
