### ISSUE TITLE
UPnP Support

### ISSUE THREAD

**Issue by russwentz** [GrinPlusPlus/GrinPlusPlus#36]
UPnP support for eventual HTTP grin transfer and incoming connections for those that have trouble port forwarding/cannot port forward.

**Comment by DavidBurkett** [comment]
I'm planning on using Magic Wormhole for this. I'll leave this open for now, as a possible fallback.

**Comment by DavidBurkett** [comment]
I got Magic Wormhole working, but chose not to release it since there are already 5-6 ways to send Grin, and adding another would further delay standardization. Grin is looking at using i2p which will solve the NAT issues and provide privacy at the same time. I'll be implementing that instead.
