### ISSUE TITLE
Detecting a forked chain?

### ISSUE THREAD

**Issue by kravens** [GrinPlusPlus/GrinPlusPlus#38]
While the rest of the Grin network is on block 102248, my Grin++ node seems to have gotten stuck at a dead end or fork on block 94976.
![image](https://user-images.githubusercontent.com/9646902/55119268-7f06c000-50f1-11e9-8971-be9b8bf0b97b.png)
Is there a good way for the node to recognize it is stuck at a lower cumulative difficulty and switch over to the heaviest chain?

Update: after node restart it does detect and sync to the latest block!

**Comment by DavidBurkett** [comment]
Glad to hear it synced. Looks like your issue was you didn't have enough peers. I've done a lot of work around that area these past few days that probably isn't pushed yet. In the meantime, port forwarding on your router should help. 

Did you build from master, or use one of the release binaries?

**Comment by kravens** [comment]
I use the release binary from v0.1.0, at least I think I do, might have mixed them up...

**Comment by DavidBurkett** [comment]
This is resolved in the latest release (v0.2.0). It comes with a UI, but you can still find GrinNode.exe in the bin folder, if you want to continue to run just that.
