### ISSUE TITLE
[question] tx slate (json) from Grinmint

### ISSUE THREAD

**Issue by mo35** [GrinPlusPlus/GrinPlusPlus#40]
is there way (or planned in future) how to use tx slate (json) from Grinmint ?

**Comment by DavidBurkett** [comment]
You can open the json file by clicking receive and changing the filter to show all files /extensions. Alternatively, you can change the file extension to '. tx' and you should be able to open it by clicking receive. If successful, it will create a new file with the same name, and the extension ". response". That can then be uploaded to Grin mint to "finalize" the transaction.

**Comment by mo35** [comment]
tried that , didnt had any visual feedback from wallet that anything is imported

**Comment by DavidBurkett** [comment]
Hmm. Can you check if it created a '. response' file?

**Comment by mo35** [comment]
not that i can find it , checked location from where i loaded tx file , so does under user profile , wallet dir.
nothing there

**Comment by DavidBurkett** [comment]
OK, definitely failed, but error message should've displayed. I'm not at my computer right now, but if you don't mind installing postman, I can send you the steps tonight to bypass the UI and call directly into the rest API. That should tell us where it's failing. 

Is there a "message" field in the json?

**Comment by mo35** [comment]
you can send me howto i will look into (tho im in EU , and its 11pm currently for me , so prolly tomorrow)

its present , but w/o data :
"message":null

**Comment by DavidBurkett** [comment]
Chrome should be fine. I'll send you the steps in a few hours. Thanks for your patience!

**Comment by DavidBurkett** [comment]
I was able to get my hands on a slate from Grinmint, and have since figured out the issue. They're using an older version of Grin than I thought to generate the slates. I'll make a change to the Grin++ code to handle it, but you can get away with just adding "version":0 as the first field in your slate from Grinmint.  So for example,

Before:
`{"num_participants":2,"id":"b565d547-10c5-4cb3-985b-1a0a4a7d5966" ...... }`

After:
`{"version":0,"num_participants":2,"id":"b565d547-10c5-4cb3-985b-1a0a4a7d5966" ...... }`

**Comment by mo35** [comment]
I will test it in evening. Thanks for quick help and keep up good work !

**Comment by DavidBurkett** [comment]
I'm assuming all went well, so I'm closing this. If the issue persists, feel free to re-open it.

**Comment by mo35** [comment]
something again changed with grinmint , no response files are generated with 0.6.4

slate header looks like :
{"version_info":{"version":2,"orig_version":2,"block_header_version":2},"num_participants":2,

**Comment by DavidBurkett** [comment]
You'll have to request a new file and try again. It's a latent Grin++ bug that should be fixed in the next version. It will be released soon. 
Here's the original issue: https://github.com/GrinPlusPlus/GrinPlusPlus/issues/46
