### ISSUE TITLE
JavaScript error at launch

### ISSUE THREAD

**Issue by kravens** [GrinPlusPlus/GrinPlusPlus#41]
Unable to succesfully start the GUI app Grin++.exe:
![image](https://user-images.githubusercontent.com/9646902/55439948-6c373400-55a6-11e9-8ed8-f343c54081da.png)

Using Grin++ v0.2.0 on Windows 10 (v10.0.17763 Build 17763)

**Comment by DavidBurkett** [comment]
I think you probably just need to download and install vcredist_x64 from here https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
Let me know if that works!

**Comment by DavidBurkett** [comment]
Feel free to re-open if you're still having the issue.

**Comment by kravens** [comment]
Version 0.3.1 does not crash :)
