### ISSUE TITLE
v0.3.0 error importing tx slate, created from different wallet locally 

### ISSUE THREAD

**Issue by mo35** [GrinPlusPlus/GrinPlusPlus#42]
I wanted to shuffle some Grins locally between wallets on v.0.3.0 via tx slates. Wasnt unable to , on secondary wallet it fails importing slate file with attached exception.
![err](https://user-images.githubusercontent.com/16078512/55733268-3373e080-5a26-11e9-8105-25ec4b96a8d2.JPG)

**Comment by DavidBurkett** [comment]
I was just able to recreate that issue. I'm looking into it now.

**Comment by DavidBurkett** [comment]
Issue is resolved. I'm packaging a new release. v0.3.1 will be available shortly. Thanks for finding this issue!

**Comment by DavidBurkett** [comment]
https://github.com/GrinPlusPlus/GrinPlusPlus/releases/tag/v0.3.1
Feel free to re-open this issue if the problem persists.
