### ISSUE TITLE
Dowload of the latest version of wallet not working?

### ISSUE THREAD

**Issue by matthieuvandiepen** [GrinPlusPlus/GrinPlusPlus#47]
Dowload of the latest version of wallet not working?

I tried several times to download the wallet, version V0.4.0 but it stops somewhere inbetween in the download process.

**Comment by DavidBurkett** [comment]
Sorry I just saw this. I haven't had anyone else report having this problem, and it downloads fine for me. I'll have a new version out next weekend that should be 1/3 the size, so hopefully you'll be able to download that one.

**Comment by DekuDigital** [comment]
I have a fairly decent Windows machine and it's taking 10 minutes plus to unzip the 22,000+ files.
Is that normal?

**Comment by DavidBurkett** [comment]
Yes, that's because of the way I packaged Electron. The next release is just a day or 2 away and doesn't have this issue. It just uses a 50mb installer that takes 10-20s to install.

**Comment by DekuDigital** [comment]
Ok good to know. I'll await that version :)
Appreciate the speedy response.

**Comment by DavidBurkett** [comment]
New version has been released that should be quicker to download and install.
