### ISSUE TITLE
javascript error when logout

### ISSUE THREAD

**Issue by hkingofsaga** [GrinPlusPlus/GrinPlusPlus#48]
![image](https://user-images.githubusercontent.com/466871/58226909-43881b00-7d5b-11e9-82ed-5821c136c34d.png)

**Comment by rrahul9637** [comment]
facing the same problem while login into v.5.0.0

**Comment by DavidBurkett** [comment]
Should be fixed in v0.5.4. Feel free to re-open if the problem persists.
