### ISSUE TITLE
No able to receive grin from kucoin

### ISSUE THREAD

**Issue by rrahul9637** [GrinPlusPlus/GrinPlusPlus#49]
hello sir,

i am No able to receive grin from kucoin. their support is saying your  address is not showing online.

Kindly help.

**Comment by DavidBurkett** [comment]
Which address? Grinbox or http?

**Comment by rrahul9637** [comment]
http address

**Comment by DavidBurkett** [comment]
You still have to setup port forwarding on your router for port 3415. All wallets require that to receive via http. The hope is that exchanges will start supporting file transfer instead. 

You should be able to Google port forwarding for your router model. If you're not able to figure it out, ask on one of the telegram groups or on the support channel. https://gitter.im/grin_community/support

**Comment by rrahul9637** [comment]
i am not using a router, i am using mobile internet.

**Comment by zelva1** [comment]
I have the exact same problem. I wanna withdraw from Kucoin, I enter my http from receive in Grin++. They say it's a failed address.

**Comment by DavidBurkett** [comment]
Http requires users to setup port forwarding. There's no easy way around this.

**Comment by DavidBurkett** [comment]
As of v0.5.3, you should be able to receive Grin via http without needing to setup port forwarding.
