### ISSUE TITLE
can't recieve from ironbelly wallet via file

### ISSUE THREAD

**Issue by pro2pop** [GrinPlusPlus/GrinPlusPlus#50]
HI
loading ironbelly grinslate file, recieving "unknown error" red label.

**Comment by DavidBurkett** [comment]
Can you open the slate with a text editor and see if you can find the version (0, 1, or 2)

**Comment by pro2pop** [comment]
"version":1

**Comment by DavidBurkett** [comment]
Ah, v1 was only used for a very short period of time in one of the beta versions, and there are a couple different incompatible "v1" versions. Do you mind uploading the slate, or emailing it to me (email is in github profile) so I can figure out which one it is?

**Comment by pro2pop** [comment]
done

**Comment by DavidBurkett** [comment]
Replaced by: https://github.com/GrinPlusPlus/GrinPlusPlus/issues/51

For a workaround, users can change message and message_sig to null.
