### ISSUE TITLE
Cannot login to account using perfect username:pass/memseed

### ISSUE THREAD

**Issue by mrselfdestruct6** [GrinPlusPlus/GrinPlusPlus#52]
installed grin++ today and instantly after creating a wallet i can not log back into the same wallet using perfect memseed/ password/username, ive already transferred grin into this wallet and dont want to lose it

**Comment by mrselfdestruct6** [comment]
Ps when using restore wallet function i get ERROR
Invalid wallet words entered. Please make sure all words are correct, and are separated by a single space.
when using open wallet i get failed to login username or password is incorrect.

**Comment by DavidBurkett** [comment]
3 people had similar issues a month or so back, and I thought I had it fixed. Don't worry though, your funds are safe. Can you tell me about your pc specs and operating system?

Try restarting your computer to make sure there aren't multiple instances running. If that doesn't work, rename your c:/users/<username>/.GrinPP/MAINNET/WALLET folder and try restoring again.

**Comment by mrselfdestruct6** [comment]
hey thanks for the hasty reply my PC is windows 7 HP,  AMD FX8350 4GHz CPU, radeon 480 GPU 16GB DDR4 ram, no process in taskmanager related to grin++ i will attempt reboot and move grin++ to a root directory

**Comment by mrselfdestruct6** [comment]
reboot, moved grin++ to root C:/ edit wallet to wallet.bak and still same issue running grin++ in admin privleges aswell

**Comment by DavidBurkett** [comment]
Hmm. Can you upload the logs from the MAINNET/NODE/LOGS folder?

**Comment by mrselfdestruct6** [comment]
[GrinPlusPlus.log](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3225035/GrinPlusPlus.log)

sure thing hope this helps

**Comment by DavidBurkett** [comment]
Thanks for this. It looks like you were able to create a wallet twice, but you were never able to successfully login with either, correct? Unfortunately I'm not logging out the reason it's failing so if you don't mind, I'd like to send you a debug version in a few hours that logs out every function call. I won't log any personal info, obviously. You're one of the few that can consistently recreate this, so using you to track down the issue would really help me a lot!

**Comment by mrselfdestruct6** [comment]
yeah that was the case, lol my mum always said i was special :) sure thing hit me up i need a hardwallet for windows so happy to help

**Comment by DavidBurkett** [comment]
Want to try logging in using this version, and once it fails, exit Grin++ and then send me the logs from %USERPROFILE%/.GrinPP/MAINNET/NODE/LOGS?

https://github.com/GrinPlusPlus/GrinPlusPlus/releases/tag/v0.5.2

**Comment by mrselfdestruct6** [comment]
hey  sorry to say but im having issues with the installer it rushes the first 50% then hangs in the middle

**Comment by DavidBurkett** [comment]
Try uninstalling the old one first, if you haven't already.

**Comment by mrselfdestruct6** [comment]
i did a quick delete originally just restored and tried to use the uninstaller, it launches the yes/no prompt then exits before uninstalling

**Comment by mrselfdestruct6** [comment]
did 2 clean uninstalls and 2 clean installs same issue heres the log
[GrinPlusPlus.log](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3227115/GrinPlusPlus.log)

**Comment by DavidBurkett** [comment]
I didn't try to fix the issue, only add more logging so I could find the root cause. The logs say there is no account with that username. Try creating a new account with a different username and then logout and log back into the new account to see if it has the same issue

**Comment by mrselfdestruct6** [comment]
made a few one with original name second with different name, couldnt pass MEMseed stage of account creation and third which succeeded account creation
[GrinPlusPlus.log](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3227208/GrinPlusPlus.log)

**Comment by DavidBurkett** [comment]
Were you able to login to the account you just created with the original name? If so, then everything appears to be working during login. Let's try to use your original wallet database. Do you still have the original wallet folder that I asked you to name 'WALLET.Bak'?

**Comment by mrselfdestruct6** [comment]
no same issue with orginial named account and sme issue with testerthejester account yes i do heres the zipped wallet folder and an updated log with recent login attempts
[GrinPlusPlus.log](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3227296/GrinPlusPlus.log)
[WALLET.bak.zip](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3227299/WALLET.bak.zip)

**Comment by DavidBurkett** [comment]
Thanks. I have to step away for a bit, but then I'll see what I can figure out.

**Comment by mrselfdestruct6** [comment]
no worries mate thanks for your time and effort, keep up the good work!

**Comment by DavidBurkett** [comment]
Something caused the version byte to be incorrect on the DB entry for your seed, but I haven't the slightest clue what caused that. I'll figure it out and fix it in the next version, but I just manually modified that byte in your wallet DB. Just replace `%userprofile%\.GrinPP\MAINNET\WALLET` with this one:

[WALLET.zip](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3228061/WALLET.zip)

**Comment by mrselfdestruct6** [comment]
thanks a bunch mate doing some solid work here ive grabbed the zip feel free to delete when ever
,just tried to open original and test wallet with the same issue sorry

**Comment by DavidBurkett** [comment]
Hmm. Can you send logs again? I obviously wasn't able to login, but I was able to load and deserialize the encrypted seed

**Comment by mrselfdestruct6** [comment]
[GrinPlusPlus.log](https://github.com/GrinPlusPlus/GrinPlusPlus/files/3229845/GrinPlusPlus.log)
here ya go thanks for the help

**Comment by DavidBurkett** [comment]
Hmm, it looks like it's hashing your password fine and loading the seed fine from database, but it thinks your password is wrong. Can we continue this in email so we're not spamming alerts to all watchers? Davidburkett38@gmail.com

**Comment by evangerardmiller** [comment]
I have this issue too, was it solved?

**Comment by DavidBurkett** [comment]
@evangerardmiller What version are you running?

**Comment by evangerardmiller** [comment]
0.5.4 on windows 7 like op. Tried reboot. Have made a couple accounts where this happened

**Comment by DavidBurkett** [comment]
@evangerardmiller There's a support button in the upper right corner. Can you click on that and fill out the form? It should upload your logs to me so I can see if you're still having the same issue. It does not send any private keys or anything that would allow me to access your grins.

**Comment by evangerardmiller** [comment]
ok sent

**Comment by DavidBurkett** [comment]
@evangerardmiller Looks like you're having the same issue. From your logs:

```
[2019-06-17 19:40:30.713] [LOGGER] [debug] THREAD(ID:6328) => SeedEncrypter::DecryptWalletSeed - Hashing password.
[2019-06-17 19:40:30.924] [LOGGER] [debug] THREAD(ID:6328) => SeedEncrypter::DecryptWalletSeed - Decrypting with AES256.
[2019-06-17 19:40:30.924] [LOGGER] [debug] THREAD(ID:6328) => SeedEncrypter::DecryptWalletSeed - Comparing HMAC.
[2019-06-17 19:40:30.924] [LOGGER] [error] THREAD(ID:6328) => SeedEncrypter::DecryptWalletSeed - HMAC invalid.
[2019-06-17 19:40:30.924] [LOGGER] [error] THREAD(ID:6328) => SessionManager::Login - Wallet seed not decrypted. Wrong password?
```

I really wish I could tell you what's causing the issue, but I unfortunately don't know. _Some_ windows 7 users have the issue, and it works fine for others. I'll post back here once I finally track it down, but I've been busy with planning for the first HF, so it may be a while. In the meantime, maybe try Niffler (https://github.com/grinfans/Niffler)? You can enter your same recovery seed and it should find your coins.

**Comment by evangerardmiller** [comment]
Ok thanks

**Comment by evangerardmiller** [comment]
I ran Grin++ on a windows 10 machine and was able to recover

**Comment by joanrs** [comment]
Hello,

 I have the same issue described here on windows7 ... "installed grin++ today and instantly after creating a wallet i can not log back into the same wallet using perfect memseed/ password/username,"

**Comment by DavidBurkett** [comment]
Fixed in: https://github.com/GrinPlusPlus/GrinPlusPlus/releases/tag/v0.6.1

After installing 0.6.1, go to settings in the top right, check the checkbox for enhanced database. Click Save. Exit Grin++, wait a second or two, and then reopen it.
