### ISSUE TITLE
Segmentation fault on kill

### ISSUE THREAD

**Issue by garyyu** [GrinPlusPlus/GrinPlusPlus#60]
`Segmentation fault: 11`

when Ctrl+C to exit.

**Comment by DavidBurkett** [comment]
I've seen this one before on a mac. It has to do with how we shutdown our RocksDB database. RocksDB is really finicky about shutdowns. It's almost better to just not bother with deleting the db memory and just ending the process when we're done

**Comment by DavidBurkett** [comment]
Fixed in v0.6.2
