### ISSUE TITLE
Updater causes unclean shutdown leading to data corruption

### ISSUE THREAD

**Issue by DavidBurkett** [GrinPlusPlus/GrinPlusPlus#65]
Several users reported corrupted data after updating. The cause appears to be due to the updater not calling GrinNode's shutdown API.

**Comment by kravens** [comment]
I noticed a crash about a second after starting v0.5.5 on W10, don't know why... maybe I should do a clean install instead of update?

**Comment by DavidBurkett** [comment]
@kravens Uninstalling doesn't actually remove your chain_data or wallet. If you want, you can delete %userprofile%/.GrinPP/MAINNET/NODE and then resync

**Comment by kravens** [comment]
@DavidBurkett That indeed works! Now it is syncing and validating again without crashing :)

**Comment by DavidBurkett** [comment]
@kravens Great! I'll be adding a button that resyncs automatically next release to make it a little easier

**Comment by DavidBurkett** [comment]
0.5.6 has a Resync Blockchain button in the settings modal:
![image](https://user-images.githubusercontent.com/24623306/59989806-a4329e00-960e-11e9-90e0-03295fb5a9eb.png)
