### ISSUE TITLE
Switch to 12 words seed phrase

### ISSUE THREAD

**Issue by vcorem** [GrinPlusPlus/GrinPlusPlus#66]
For usability purpose, I suggest that Grin++ will switch to generating 12 words seed instead of 24, while still allowing recovery with 24 words to support the official client. Yes, it will cause users to be locked-in to Grin++, at least until the official client will implement it as well. A remedy might be an advanced option that will allow 24 words seed creation.

**Comment by DavidBurkett** [comment]
This option has been added to the upcoming 1.0.0 release
