### ISSUE TITLE
Version 0.6.1 how to choose setup path ?

### ISSUE THREAD

**Issue by joanrs** [GrinPlusPlus/GrinPlusPlus#68]
Please I need to install it on a different location from C:\

I need to choose blockchain location also ... 

Many thanks !!

**Comment by DavidBurkett** [comment]
There's no way to change the install location, and no plans to add one anytime soon (it messes with auto update). You can change where the node and wallet data is stored, if you want. You'll have to modify `DATA_PATH` in `%userprofile%/.GrinPP/MAINNET/server_config.json`.

**Comment by binarygeek** [comment]
Where in the file and in what format is it expected? Right now all I see in the file is:

`{
	"WALLET" : 
	{
		"DATABASE" : "SQLITE"
	}
}`

A wiki on the various keys and values for server_config.json would be nice and helpful.

**Comment by DavidBurkett** [comment]
So in your server_config.json, you could just add it before "WALLET" like so:

```
{
	"DATA_PATH" : "C:/new/path/here",
	"WALLET" : { "DATABASE" : "SQLITE" }
}

**Comment by binarygeek** [comment]
That worked great. thanks!
