### ISSUE TITLE
v0.6.1 for MacOS can't run GrinNode

### ISSUE THREAD

**Issue by rigamp** [GrinPlusPlus/GrinPlusPlus#70]
When opening Grin++, this error is displayed:

Error occurred in GrinNode process. Try restarting Grin++. Error: 
Error: Command failed: ./GrinNode --headless

Old version v0.5.4 loads node.

**Comment by DavidBurkett** [comment]
Try deleting "~/.GrinPP/MAINNET/NODE" and see if it resyncs

**Comment by rigamp** [comment]
Thank you.  Tried it and same error after it rebuilt the directory.  This error appears immediately when opening app, before wallet options are shown.

Tried reverting Grin++ back to 0.5.4 and no error.

**Comment by DavidBurkett** [comment]
Continuing to revert back to 0.5.4 will cause issues. The old version provides no value anymore since the hardfork occurred, so it's best to just delete it. Can you try deleting once again just to be sure 0.5.4 wasn't causing issues, and if you continue to have the issue, please upload ~/.GrinPP/MAINNET/NODE/LOGS/GrinPlusPlus. log

**Comment by rigamp** [comment]
I started with a fresh install on 0.6.1 and got the error. Tried previous releases until a version worked.  0.5.4 worked.

0.5.4 GrinPlusPlus.log has entries, but 0.6.1 is empty (zero bytes).

If I wipe ~/GrinPP completely then run 0.6.1, I get the error on starting app & empty logfile.

![Grin___v0_6_1](https://user-images.githubusercontent.com/45978089/61596101-75cbc280-abbc-11e9-8f43-1e2046d37381.jpg)

![GrinPP](https://user-images.githubusercontent.com/45978089/61596111-8d0ab000-abbc-11e9-9403-889902320a21.jpg)

**Comment by DavidBurkett** [comment]
Thanks for the explanation. What Mac OS version are you running?

**Comment by rigamp** [comment]
Mojave 10.14.5.

Your response time is mind-blowing.  Much respect sir.

**Comment by DavidBurkett** [comment]
Honestly not sure what's going on. Mojave is what I test on, and I haven't added any new dependencies since v0.5.4. v0.6.2 is set to come out in a few days, so I'll make sure I add some better error handling that should at least tell us what's wrong. I'll let you know once the new version is out.

**Comment by huyxm** [comment]
I got the same error message. Running on macOS High Sierra 10.13.6

**Comment by DavidBurkett** [comment]
I think I may have figured out what's going on. @rigamp @huyxm What year & model of mac do you have?

**Comment by huyxm** [comment]
2013 macbook pro is the year & model.

**Comment by DavidBurkett** [comment]
@rigamp @huyxm Here's a pre-release of 0.6.2. I believe it should fix your issues: https://keybase.pub/dburkett/GrinPlusPlus-0.6.2.dmg

**Comment by huyxm** [comment]
Works perfectly now. Thank you!

**Comment by DavidBurkett** [comment]
I'm closing this since 0.6.2 should be released soon. @rigamp feel free to reopen if it's still a problem for you.

**Comment by Hansie020** [comment]
Hi @DavidBurkett 

I just installed version 0.6.3 and got the same error as @rigamp 
After installing 0.6.4 the issue remains. I also have a macbook pro 2013 and am running Mojave 10.14.6. 
The combination of Grin++ 0.6.3 and Mojave 10.14.2 gave the same problem.

What do you recommend?

Thanks for your reply!

**Comment by DavidBurkett** [comment]
Try deleting ~/.GrinPP/MAINNET/NODE. Then reopen. Not sure if that doesn't work. The requirements for 0.6.2 and up should be minimal.

**Comment by Hansie020** [comment]
Thanks for your quick reply @DavidBurkett 
The suggested solution does not work unfortunately. Any other suggestion would be appreciated.
Where can I find the reqs for 0.6.2?

**Comment by DavidBurkett** [comment]
I'm not fancy enough to have actual documented requirements, but it should be as simple as: High sierra or later
Is there anything in ~/.GrinPP/MAINNET/NODE/LOGS?

**Comment by Hansie020** [comment]
It seems that I meet the reqs. The ui.log file contains the following:

`[2019-08-07 12:49:15.495] [info] pkill executed
[2019-08-07 12:49:15.631] [info] GrinboxConnection: Message received {"type":"Challenge","str":"7WUDtkSaKyGRUnQ22rE3QUXChV8DmA6NnunDYP4vheTpc"}
[2019-08-07 12:49:16.757] [info] Checking for update
[2019-08-07 12:49:18.396] [info] Update for version 0.6.4 is not available (latest version: 0.6.4, downgrade is disallowed).
[2019-08-07 12:49:19.245] [info] Failed to connect to node.
[2019-08-07 12:49:19.246] [info] Failed to connect to node.
[2019-08-07 12:49:21.025] [info] Failed to connect to node.
[2019-08-07 12:49:21.025] [info] Failed to connect to node.
[2019-08-07 12:49:23.247] [info] Failed to connect to node.
[2019-08-07 12:49:23.248] [info] Failed to connect to node.
[2019-08-07 12:49:25.491] [info] Failed to connect to node.
[2019-08-07 12:49:25.492] [info] Failed to connect to node.
[2019-08-07 12:49:27.391] [info] mainWindow.on('close')`

**Comment by DavidBurkett** [comment]
From the terminal, type the following and press enter:
`/Applications/Grin++.app/Contents/Resources/app.asar.unpacked/app/bin`

What does this output?

**Comment by Hansie020** [comment]
It give the following output:
`-bash: /Applications/Grin++.app/Contents/Resources/app.asar.unpacked/app/bin: is a directory
`

**Comment by DavidBurkett** [comment]
Oops, forgot the last part:
`/Applications/Grin++.app/Contents/Resources/app.asar.unpacked/app/bin/GrinNode`

**Comment by Hansie020** [comment]
It gives:
`Illegal instruction: 4`

**Comment by DavidBurkett** [comment]
Ok, last thing to look at. Can you give me the output of:
`otool -L /Applications/Grin++.app/Contents/Resources/app.asar.unpacked/app/bin/GrinNode`

I can't recall if otool comes by default with mac or not, so if it asks you to install dev tools, I'd appreciate if you did, but understand if you don't want to.

**Comment by Hansie020** [comment]
No problem. it was already installed. Here is the output:
`/Applications/Grin++.app/Contents/Resources/app.asar.unpacked/app/bin/GrinNode:
	@executable_path/libP2P.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libBlockChain.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libConfig.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libWallet.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libDatabase.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libPoW.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libTxPool.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libPMMR.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1570.15.0)
	@executable_path/libWalletDB.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libCrypto.dylib (compatibility version 0.0.0, current version 0.0.0)
	@executable_path/libInfrastructure.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@executable_path/librocksdb.6.dylib (compatibility version 6.0.0, current version 6.2.0)
	@executable_path/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.24.0)
	@executable_path/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
`

**Comment by DavidBurkett** [comment]
Everything looks fine. I haven't the slightest clue what's wrong. If you're a developer, you could try debugging with gdb, or if you want to set up ssh access for me, I could also try. Other than that, I'm not really sure how to proceed, unfortunately.

**Comment by Hansie020** [comment]
Thanks for investing some time in this issue. How can i setup SSH access for you?

**Comment by DavidBurkett** [comment]
Let's move this to email so we're not advertising IPs and stuff. Can you email me? davidburkett38@gmail.com
