### ISSUE TITLE
Timeout when try to report from the app

### ISSUE THREAD

**Issue by matthieuvandiepen** [GrinPlusPlus/GrinPlusPlus#74]
Hi David I get a Timeout when try to report from the app

it says, Failed to submit: Operation timed out.

What I tried to report ;-)

I want to sent Grin from the Bitmesh exchange to my (great) Grin++ wallet
- I tried with my grinbox address, but Bitmesh has troubles to support Grinbox
- then I tried with https://a90dbf73.ngrok.io 

Now Bitmesh says: Audit is failed: Address not reachable(tried 4 times), please set a new one

If I look at the withdrawal instructions of Bitmesh it says:

1. IP+port format,  e.g.  http://xxx.xxx.xxx.xxx:3415
2. grinbox format, e.g. grinbox://gVtJUDJaFbMqVntTfSGkswGaxcbFhU42Yyxx1FkJvNDfvHKDB6b9

The grinbox option is broken on the side of Bitmesh for some reason (before it worked), but it doesn't work either if I use the Ngrok address.

Do I need to add a port to the url?

Do you have any suggestions?

Thanks!

**Comment by DavidBurkett** [comment]
Thanks for reporting these issues. I don't host the bug report service, one of the community members does, so not sure what happened. It appears to be back online now.

The port would just be 443. It's a bit redundant, but you could use: https://a90dbf73.ngrok.io:443
Also, a bit redundant, but you could add the `grinbox://` to the front of your grinbox address

Please note that with ngrok, you must stay online until they try to send the funds. If you logoff, you will lose that ngrok address, and will get a new one next time you login. Also important to note, the ngrok address times out in 8 hours, so Grin++ will generate a new one every 8 hours.

Let me know if either of those suggestions works for you.

**Comment by matthieuvandiepen** [comment]
Thanks David, I tried to withdraw with this:
https://5cf13d4a.ngrok.io:443

But no luck

But now I'm thinking, maybe they expect an ip number?

So I looked up the IP of https://5cf13d4a.ngrok.io

It says, 3.19.114.185 (https://adresults.nl/tools/website-ip-checker/?autoloadform=true&url=https%3A%2F%2F5cf13d4a.ngrok.io&=)

Do you think it's safe totry to withdraw with?:

https://3.19.114.185:443

Thanks again!

**Comment by DavidBurkett** [comment]
No, probably not. Do you know how to setup port forwarding? If you forward port 3415, then you can go to whatismyip.com to get your public IP. Then you can use http://<YourPublicIP>:3415

**Comment by DavidBurkett** [comment]
Closed due to inactivity. If the issue still persists in Grin++ 0.6.4, feel free to reopen.
