### ISSUE TITLE
GrinNode process left running after closing app

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#84]
I like Grin++, it's quite cool. Thanks for creating it. I installed the 0.6.4 MacOS version

However, after installing it and closing it, i noticed my battery was going at a much faster rate than before, until I noticed that a `GrinNode` process is left running in the background after closing Grin++ (real quit).

Is this a bug or intentional? If the latter, then it's not so cool (are you aiming to increase the number of Grin++ nodes in the network?). If intentional, then the proper way to do it is to 

- inform the user about it, and
- add an unchecked (opt-in, not opt-out) option to leave node running after closing

**Comment by aleqx** [comment]
Also, I would venture a guess than a good number (majority?) of the Grin++ nodes currently online are unintentional because of this.

**Comment by DavidBurkett** [comment]
It's a bug. For now, you have to close using the x, not using the quit button in the top menu. 

Those percentages were from back before there were any mac users.

**Comment by aleqx** [comment]
I see. I'm always closing using Cmd+Q. On MacOSX, since the "x" doesn't actually kill apps in general on macosx, so i never use the x.

**Comment by DavidBurkett** [comment]
Right, all of the closing code for electron was written and thoroughly tested for windows, and didn't port well to Mac. Managing multiple child processes gracefully is actually pretty tricky with electron on mac, and I apparently don't do a very good job at it. Sorry, I will try to find a fix for this.

**Comment by aleqx** [comment]
You did a great job on most things :). Kill process tree should work for this

**Comment by DavidBurkett** [comment]
> You did a great job on most things :). Kill process tree should work for this

It's not really that simple. We need to ensure safe shutdown of the child process (to avoid data corruption), so just killing isn't really an option. The bigger problem is not really how to end the child process, but _when_ to end it. This all depends on which messages electron sends during Cmd+Q and in which order they are sent. I'll figure all that out though and safely handle all methods of closing before the next release.

**Comment by aleqx** [comment]
If clicking x does what you want, then shouldn't programming "quit" (from the menu) and cmd+q to do the same thing work?

**Comment by DavidBurkett** [comment]
No, unfortunately. I don't have control over those buttons. I'm at the mercy of electron, so am forced to handle their non-intuitive, under-documented messages instead.

**Comment by DavidBurkett** [comment]
Should be fixed on 0.7.2. Feel free to reopen if the issue remains.
