### ISSUE TITLE
allow custom minimum number of confirmations for spendable output

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#86]
Could you please make this a config options (or better yet, a GUI option)? Basically, the `--min_conf` command line option of the official wallet.

Currently you hardcoded it to 10 in (I did notice the `TODO` comment) https://github.com/GrinPlusPlus/GrinPlusPlus/blob/4b7384f025ff86288652a51dec3d8835e6dd4ad8/src/Config/ConfigReader.cpp#L179

**Comment by DavidBurkett** [comment]
Sure, as you can see, that was the intention. Just never added the few lines needed to read it. I'll add it to the settings window, as well.

**Comment by DavidBurkett** [comment]
If you think of any other settings you would like to see added, feel free to list them here or in a new issue. The config logic could use some work, so I'll use the opportunity to clean it all up.

**Comment by aleqx** [comment]
I would quite like to see the actual timestamp of transactions (YYYY-mm-dd HH:MM:SS) rather than relative times or date only. I would also like to see all transactions (paginate/scroll) rather than just the most recent 10. I can't recall if it's possible to see when a transaction was sent to the pool (as in btc, eth, and others), it would be nice to show that too (gives an idea of how long it takes for a transaction to get confirmed).

Also, the "Date/Time" of transactions is actually wrong - I believe this is a bug. It seems Grin++ takes the date/time as the time that it (Grin++ client) fetched them from the chain, rather than the timestamp of the block where the transactions were mined. It's this latter timestamp that should be displayed (the former is pretty useless to me).

**Comment by DavidBurkett** [comment]
Thanks for fixing this!
