### ISSUE TITLE
bug in transaction date/time (?) and request for actual timestamps

### ISSUE THREAD

**Issue by aleqx** [GrinPlusPlus/GrinPlusPlus#88]
Continuing from https://github.com/GrinPlusPlus/GrinPlusPlus/issues/86

A possible bug (I think): the "Date/Time" of transactions is wrong, as in it's not the time the transaction was created (reached tx pool) nor when it was confirmed. It looks like Grin++ takes the date/time as the time that it (i.e. the Grin++ wallet) fetched it from the chain, because I can see lots of them having the same date/time, but i know they were made on different days. 

Also, could you please display the actual timestamp (YYYY-mm-dd HH:MM:SS) rather than relative time or just dates?

It would be good to show both the time the tx was created (reached tx pool) and when it was confirmed. If you had to pick only one then it's best to display the tx pool time while it's not yet confirmed, and then the confirmation time.

It would also be nice to be able to see all transactions (paginate/scroll) rather than just the most recent 10.

**Comment by DavidBurkett** [comment]
As of 0.7.4, future restores will no longer have this problem.

**Comment by aleqx** [comment]
Can 0.7.4 also correct all timestamps of existing transactions if I refresh?

**Comment by DavidBurkett** [comment]
No unfortunately. The current fix does not modify any existing date/times. If restoring isn't an option for you, we can look into options for fixing wrong timestamps
