### ISSUE TITLE
Windows symlinks not supported 

### ISSUE THREAD

**Issue by ahilis** [GrinPlusPlus/GrinPlusPlus#96]
![image](https://user-images.githubusercontent.com/6560240/68643137-2d049480-0532-11ea-9f95-7079898a1d81.png)

and a few rows from log:

[2019-11-12 09:48:29.548] [info] GrinboxConnection: Connecting to grinbox.io
[2019-11-12 09:48:30.001] [error] GrinboxConnection: Error thrown - Unexpected server response: 404
but ginbox.io is available from browser, what's wrong?
the error appeaed when I moved .GrinPP folder to another disk using symlink on windows 10

**Comment by DavidBurkett** [comment]
Hmm, apparently it doesn't work with symlinks. You can get rid of the symlink and just change the data path in the config json (should be in .GrinPP dir).

**Comment by ahilis** [comment]
Yes, your solution works fine, thank you
